I2C_ENABLE = yes
CONSOLE_ENABLE = yes
I2C_DRIVER_REQUIRED = yes
BOOTMAGIC_ENABLE = yes
VIA_ENABLE = yes

ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes

#BACKLIGHT_ENABLE = yes
#BACKLIGHT_DRIVER = software
