#pragma once

#define I2C_MASTER
#define I2C1_SDA_PIN GP2
#define I2C1_SCL_PIN GP3
#define I2C_MASTER_ENABLE
#define BOOTMAGIC_ROW 0
#define BOOTMAGIC_COLUMN 0

#define ENCODER_A_PINS { F4 }
#define ENCODER_B_PINS { F5 }

#define WS2812_DI_PIN B6
#define RGBLIGHT_LED_COUNT 3
#define RGBLIGHT_SLEEP
#define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_STATIC_LIGHT
#define RGBLIGHT_DEFAULT_HUE 0

#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_TWINKLE

